name: leetcode_dart_solutions
description: "A collection of LeetCode problem solutions implemented in Dart."
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  test: ^1.24.0
